### ISSUE TITLE
Add events parameter in connect

### ISSUE THREAD

**Issue by nicchap** [ofbeaton/phpami#1]
AMI is very message intensive and there are times when you do not want these events to be sent when connecting to a server. By adding the an optional eventmask (ON/OFF) parameter to the connect command, then we can prevent those events from being sent.

It's also good to flush any events in the buffer once connected if the evenmask parameter is set to OFF.

**Comment by ofbeaton** [comment]
Thank you for the feature request.

I just put out [Release 0.5.0](https://github.com/ofbeaton/phpami/releases/tag/0.5.0) which I hope addresses your issue by adding a optional 4th parameter to `connect` to call `events` with a filter. This will occur after logging in. Events will remain on by default.

Please also note [Release 0.3.0](https://github.com/ofbeaton/phpami/releases/tag/0.3.0) which added log levels so that the event logging that used to occur is now also disabled by default, but can be incrementally turned on using `setLogLevel`.

Does this suit your needs?

**Comment by nicchap** [comment]
Looks good. I will test a few scenarios and report back.

**Comment by ofbeaton** [comment]
Please re-open if you discover any problems.
